baseurl             = "https://loyaltyarm.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Nick Cobb"
title               = "Nick Cobb"
pygmentsuseclasses  = true
disqusshortname     = "cobbservations"
pluralizelisttitles = false
googleAnalytics     = "UA-98500532-1"

[permalinks]
    fixed = ":title/"
    blog  = "blog/:slug/"

[[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "/blog/"

[[menu.main]]
    name                   = "About"
    weight                 = -110
    identifier             = "about"
    url                    = "/about/"

[[menu.main]]
    name                   = "Resume"
    weight                 = -100
    identifier             = "code"
    url                    = "https://linkedin.com/in/loyaltyarm"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    latestpostscount       = 10
    i18n_flags             = false                         # whether to display small country flags for available translations
    author                 = "Nick Cobb"
    cachebuster            = true
    dateform               = "Jan 2, 2006"
    dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
    description            = ""
    email                  = "loyaltyarm@gmail.com"
    extracssfiles          = [ "/css/override.css" ]
    faviconfile            = "img/leaf.ico"
    github                 = "//github.com/loyaltyarm"
    highlightjs            = true
    lang                   = "en"
    linkedin               = "//linkedin.com/in/loyaltyarm"
    noshowreadtime         = false
    selfintro              = "A wise man never knows all; only a fool knows everything."
    twitter                = "//twitter.com/loyaltyarm"
    # highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
    avatar                 = "img/headshot.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
